spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=kitamn;encrypt=false;
    username: kitamn
    password: kitamn
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver


  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
        jdbc.time_zone: UTC
      open-in-view: false

  flyway:
    locations: classpath:db/migration
    validate-migration-naming: true

server:
  port: 8080

app:
  jwt:
    secret: 48934jsdjkans98eAdre9re0
    expiration-minutes: 240